# paths for regularly used files or programs
  
jar_path: '/home/dim26fa/coding/JavaUmsetzungSTORMSimulation/STORMVis/target/suresim_cli.jar-jar-with-dependencies.jar'
  
models: '/home/dim26fa/data/imod_models/model_1'
